### ISSUE TITLE
I fixed it

### ISSUE THREAD

**Issue by theDSi2homebrewGuy** [PretendoNetwork/Inkay#18] opened 2024-04-07 17:09 UTC
I fixed it

**Comment by ashquarky** [comment] 2024-04-13 00:57
Duplicate of #10 ..?

**Comment by theDSi2homebrewGuy** [comment] 2024-04-14 01:57
nvm I fixed it

**Comment by ashquarky** [comment] 2024-04-14 05:13
What did you do to fix it?

**Closed** 2024-04-15 02:12 UTC
