### ISSUE TITLE
Plugin Menu

### ISSUE THREAD

**Issue by memohomebrew** [PretendoNetwork/Inkay#26] opened 2024-04-29 01:19 UTC
Inkay is not on the Wii U Plugin System Config Menu

**Comment by memohomebrew** [comment] 2024-04-29 01:24
Hi pretendo team,Do yall know why Inkay  is not on plugin menu? I checked that the file is on SD:/wiiu/environments/croissant/Plugins/Inkay-Pretendo.wps (Croissant is Modded Aroma) I checked on aroma too btw No,Nothing I proved the SSSL method and Juxtapositon stuck on the intro menu (Earth and Miis and timezones)

**Comment by jonbarrow** [comment] 2024-06-04 07:41
Duplicate of https://github.com/PretendoNetwork/Inkay/issues/20

**Closed** 2024-06-04 07:41 UTC
